apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lithosphere-staging

resources:
  - ../../infra/k8s/base

namePrefix: staging-

commonLabels:
  environment: staging
  app.kubernetes.io/part-of: lithosphere
  app.kubernetes.io/managed-by: argocd
