apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lithosphere-devnet

resources:
  - ../../infra/k8s/base

namePrefix: devnet-

commonLabels:
  environment: devnet
  app.kubernetes.io/part-of: lithosphere
  app.kubernetes.io/managed-by: argocd
