apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Uncomment as manifests are added
  # - api-gateway/
  # - frontend/
  # - indexer/
  # - node/
  # - postgres/
  # - redis/
  # - monitoring/

commonLabels:
  app.kubernetes.io/part-of: lithosphere
  app.kubernetes.io/managed-by: argocd
